<a href="https://colab.research.google.com/github/Dhruvjain484/Machine-Learning-projects-for-beginner-Section-2-Classification/blob/main/Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

##Importing the dataset


In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [3]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

##Splitting the dataset


In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size = 0.2, random_state = 0)


##Scaling the dataset

In [5]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

##Training the dataset on appropriate classification model


In [6]:

# from sklearn.linear_model import LogisticRegression
# classifier = LogisticRegression()        ## accuracy_score = 92.5%

# from sklearn.neighbors import KNeighborsClassifier
# classifier = KNeighborsClassifier()      ## accuracy_score = 95%

from sklearn.svm import SVC
classifier = SVC(kernel='rbf')           ## accuracy_score = 95%

# from sklearn.naive_bayes import GaussianNB
# classifier = GaussianNB()                  ## accuracy_score = 91.25% 

# from sklearn.tree import DecisionTreeClassifier
# classifier = DecisionTreeClassifier(random_state=0)  ## accuracy_score = 90.00%

# from sklearn.ensemble import RandomForestClassifier
# classifier = RandomForestClassifier(random_state = 0)   ## accuracy_score = 92.5%

classifier.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

##Predicting the result


In [7]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [8]:
np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1)


array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0,

##Checking the accuracy


In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[55  3]
 [ 1 21]]


0.95

##Applying K-Fold Cross validation

In [10]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(classifier, x_train, y_train, cv=10)
score.mean()

0.9